version: '3.5'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - logstash

  elasticsearch:
#    build: elk/elasticsearch/
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
#      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      - xpack.security.enabled=false
      - discovery.type=single-node
      
  logstash:
#    build: elk/logstash/
    image: logstash:7.10.1
    container_name: logstash
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./elk/logstash/config:/etc/logstash/conf.d
    ports:
      - "9999:9999"
    links:
      - elasticsearch

  kibana:
#    build: elk/kibana/
    image: docker.elastic.co/kibana/kibana:7.3.2
    container_name: kibana
#    volumes:
#      - ./elk/kibana/config/:/opt/kibana/config/
#      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      elasticsearch.url: http://elasticsearch:9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch

